### ISSUE TITLE
The percentage it shows in the PR it is not the same as the summary file.

### ISSUE THREAD

**Issue by ABHammad** [eleboys/test-coverage-report-action#6]
I added this package to show the test coverage for every PR as I am using C8 package.

the result is right at file but it shows in the PR with different values No idea why?

here is my github file 
```
- name: Test Coverage
        uses: eleboys/test-coverage-report-action@v1.0.2
        id: report
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ./test-results/test-coverage/coverage-summary.json
          title: Test Coverage
      - name: Print the output summary
        run: echo "Report coverage json ${{ steps.report.outputs.summary}}"
```

here is the total from the summary file 

```
"total": {
    "lines": { "total": 2631, "covered": 656, "skipped": 0, "pct": 24.93 },
    "statements": { "total": 2631, "covered": 656, "skipped": 0, "pct": 24.93 },
    "functions": { "total": 104, "covered": 39, "skipped": 0, "pct": 37.5 },
    "branches": { "total": 99, "covered": 65, "skipped": 0, "pct": 65.65 },
  },
  ```

and here is the output from github action: 

```
{
"lines":{"covered":343,"skipped":0,"total":610,"pct":56.22950819672131},
"statements":{"covered":343,"skipped":0,"total":610,"pct":56.22950819672131},
"functions":{"covered":24,"skipped":0,"total":40,"pct":60},
"branches":{"covered":47,"skipped":0,"total":58,"pct":81.03448275862068}
}"
```

Any idea what is wrong?
